### ISSUE TITLE
Usage of file

### ISSUE THREAD

**Issue by amitvj24** [tkanhe/Fyers-API-Access-Token-Generation-V2#6]
Hello,
Which file do you prefer to use - Fyers_Access_Token_with_User_Agent.py or New_Fyers_Access_Token.py?

Both have comments as Optimized and shows committed on same date - so not sure which one should be selected for usage? Please advice.

**Comment by tkanhe** [comment]
I use `New_Fyers_Access_Token.py`. 
I have added `Fyers_Access_Token_with_User_Agent.py` because one user had a captcha error due to multiple requests; since the script needs to run only once daily to get the access token which will be valid for the day, `New_Fyers_Access_Token.py` will work just fine.
